fix(ImageDetection): emit hover event in mouseleave function
There is an error in Javascript that borks client side trame code
when calling emit('hover') in a watchEffect.  Steps
1. In nrtk-explorer
2. Turn on Model Inference
3. Switch to Grid view for image list
4. Error in JS console:
NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.
in
t.onmessage = async u => {
        const p = await c.processChunk(u.data, h);
        p && l(p)
    }